---
layout: page
title: "데이터 과학 -- 금융(Finance)"
subtitle: "재무제표 R 팩키지"
author:
  name: "이광춘"
  url: https://www.facebook.com/groups/tidyverse/
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
  affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography-fin.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

library(tidyverse)
library(finreportr)
```

# R 팩키지 [^xbrl-blog-edgarWebR] {#r-pkg-financial-stmt}

[^xbrl-blog-edgarWebR]: [OCTOBER 12, 2017 BY MWALDSTEIN, "Parsing Functions in edgarWebR"](https://micah.waldste.in/blog/blog/2017/10/parsing-functions-in-edgarwebr/)

- [`finstr`](https://github.com/bergant/finstr), 
- [`XBRL`]()
- [`edgarWebR`](https://github.com/mwaldstein/edgarWebR): [SEC EDGAR 시스템](https://www.sec.gov/edgar/search-and-access)에 대한 접근 인터페이스 기능을 통해 제출된 회사 재무정보 접근 제공, 단 메타데이터와 회사 정보만 제공.
- [`xbrlus`](https://github.com/bergant/xbrlus)

# [`xbrlus`](https://github.com/bergant/xbrlus) {#xbrlus-api}



```{r xbrlus-api, eval = FALSE}
# devtools::install_github("bergant/xbrlus")
library(xbrlus) 

companies <- xbrlCIKLookup(c(
  "aapl", 
  "goog", 
  "fb"
)) 

elements <- xbrlBaseElement(c(
  "AssetsCurrent",
  "AssetsNoncurrent",
  "Assets",
  "LiabilitiesCurrent",
  "LiabilitiesNoncurrent",
  "Liabilities",
  "StockholdersEquity",
  "MinorityInterest",
  "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest",
  "LiabilitiesAndStockholdersEquity"
))
```

