---
layout: page
title: 데이터 과학 -- 금융(Finance)
subtitle: "채권"
author:
    name: xwMOOC
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
```

# 3년 만기 국채 수익률 [^파이썬으로-배우는-알고리즘-트레이딩] {#treasury-bond}

[^파이썬으로-배우는-알고리즘-트레이딩]: [파이썬으로 배우는 알고리즘 트레이딩 (3쇄)](https://wikidocs.net/6661)

3년 만기 국채 수익율은 시장 금리와 같은 역할을 하기 때문에 현금배당 수익률과 비교하여 1보다 큰 경우 
주식 배당금 수익이 은행에 저금을 해서 얻는 이자 수익보다 높다는 함의를 갖는다.

$$\text{국채시가 배당률} = \frac{\text{현금배당 수익률}}{\text{3년 만기 국채 수익률}}$$

- e-나라지표: 국정모니터링지표
    - 지표 담당 : 금융위원회, 금융시장분석과, 02-2100-2856 
    - 최근 갱신일 : 2018-12-07 (입력 예정일 : 2019-01-18)

```{r treasury-bond}
library(tidyverse)
library(rvest)
library(janitor)

bond_url <- 'http://www.index.go.kr/potal/main/EachDtlPageDetail.do?idx_cd=1073'

bond_dat <- bond_url %>% 
  read_html() %>% 
  html_nodes(xpath='//*[@id="t_Table_107301"]') %>% 
  html_table() %>% 
  .[[1]]

bond_df <- bond_dat %>% 
  clean_names() %>% 
  rename(`구분` = `x`) %>% 
  filter(row_number() != 1) %>% 
  gather(`연도`, `금리`, -`구분`)

# 2018년은 월별로 되어 있어 이를 평균내기 위해서 연도별로 그룹을 묶어 평균을 냄.
bond_viz_df <- bond_df %>% 
  separate(`구분`, into=c("채권", "쓰레기"), sep="\\(") %>% 
  select(-`쓰레기`) %>% 
  mutate(`연도` = str_extract(`연도`, "^x[0-9]{4}")) %>% 
  group_by(`채권`, `연도`) %>% 
  summarise(`금리` = round(mean(`금리`),2)) %>% 
  ungroup() %>% 
  mutate(`연도` = parse_number(`연도`))

bond_viz_df %>% 
  spread(`연도`, `금리`) %>% 
  DT::datatable()

```

앞서 시장금리에 대해서 데이터를 정리한 후에 `gghighlight` 팩키지를 사용해서 가장 관심이 가는 국고채 3년과 회사채 3년에 대해서 추세를 하이라이트 기능을 동원해서 시각화한다.

```{r treasury-bond-viz}
library(extrafont)
loadfonts()
library(gghighlight)

bond_viz_df %>% 
  ggplot(aes(x=`연도`, y=`금리`, color=`채권`, group=`채권`)) +
    geom_line() +
    geom_point() +
    theme_minimal(base_family = "NanumGothic") +
    labs(x="", y="금리(%)", title="e-나라지표 시장금리 추이") +
    gghighlight(str_detect(`채권`, "3년"))

```