---
layout: page
title: "데이터 과학 -- 금융(Finance)"
subtitle: "가상화폐"
author:
- name: "이광춘"
  affiliation: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: default
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography-fin.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: red
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

library(tidyverse)
library(finreportr)
```

# 코인 거래소 [^coin-exchange] {#coin-exchange}

[^coin-exchange]: [2021년 03월 가상화폐거래소 브랜드평판](http://www.brikorea.com/contents/win_view.php?bn_id=483)

가상화폐거래소 2021년 3월 브랜드평판 30위 순위는 업비트, 빗썸, 코인원, 고팍스, 코인빗, 코빗, 포블게이트, 캐셔레스트, 프로비트, 지닥, 후오비코리아, 코인레일, 비트소닉, 비트박스, 업사이드, 비트레이드, 플라이빗, 디지파이넥스코리아, 비바코, 플라타, 올비트, 한빗코, 코인제우스, 케이덱스, 코인링크, 코인이즈, 체인엑스, 텐앤텐, 네임빗, 비트탑 순이었다.

1. 빗썸(Bithumb)
1. 업비트(Upbit)
1. 코인원(Coinone)
1. 고팍스 (Gopax)
1. 코빗(Korbit)

# 거래소 시가총액 {#marcap}

[coinmarketcap](https://coinmarketcap.com/ko/) 웹사이트에서 코인 시가총액 데이터를 가져온다.

```{r coin-marcap}
library(coinmarketcapr)
library(tidyverse)

# get_valid_currencies()

coinmarketcapr::setup(Sys.getenv("COIN_API_KEY"))

all_coins <- get_crypto_listings()

all_coins %>% names
```


