---
layout: page
title: "데이터 과학 -- 금융(Finance)"
subtitle: "SEC - 회사정보, 사업보고서, IS/BS/CF"
author:
  name: "[Tidyverse Korea](https://www.facebook.com/groups/tidyverse/)"
  url: https://www.facebook.com/groups/tidyverse/
  affiliation: Tidyverse Korea
  affiliation_url: https://www.facebook.com/groups/tidyverse/
date: "`r Sys.Date()`"
output:
  html_document: 
    include:
      after_body: footer.html
      before_body: header.html
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
bibliography: bibliography-fin.bib
csl: biomed-central.csl
urlcolor: blue
linkcolor: blue
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

library(tidyverse)
```

# `finreportr` [^blog-finreportr] [^blog-finreportr2] {#finreportr}

[^blog-finreportr]: [Aaron Mamula (November 15, 2018), "Accessing financial data from the sec part 1"](https://aaronmams.github.io/Accessing-Financial-Data-from-the-SEC-Part-1/)

[^blog-finreportr2]: [Aaron Mamula (November 16, 2018), "Accessing financial data from the sec part 2"](https://aaronmams.github.io/Accessing-financial-data-from-the-SEC-Part-2/)

[`finreportr` - Financial Data from U.S. Securities and Exchange Commission](https://github.com/sewardlee337/finreportr) 팩키지를 통해 기본적인 재무정보를 이해한다.

* `CompanyInfo()`: 회사정보
* `AnnualReports()`: 사업보고서
* `GetIncome()`: 손익계산서
* `GetBalanceSheet()`: 대차대조표
* `GetCashFlow()`: 현금흐름표

# 상장된 반도체 회사 {#listed-semiconductor-company} 

미국 증권시장에서 거래되고 있는 반도체 업체를 NYSE와 NASDAQ으로 나눠 업체목록을 작성해 보자.

```{r semi-conductor-top-nyse}
library(tidyverse)
library(rvest)

## NYSE 반도체 상장사 
nyse_semicon_url <- "https://topforeignstocks.com/stock-lists/the-complete-list-of-semiconductor-stocks-trading-on-the-nyse/"

nyse_semicon_tickers <- nyse_semicon_url %>% 
  read_html() %>% 
  html_nodes(css = '#tablepress-2661') %>% 
  html_table(header = TRUE, fill = TRUE) %>% 
  .[[1]]

nyse_semicon_df <- nyse_semicon_tickers %>% 
  janitor::clean_names() %>% 
  as_tibble() %>% 
  mutate(exchange = "NYSE")

## NASDAQ 반도체 상장사 
nasdaq_semicon_url <- "https://topforeignstocks.com/stock-lists/the-complete-list-of-semiconductors-stocks-trading-on-nasdaq/"

nasdaq_semicon_tickers <- nasdaq_semicon_url %>% 
  read_html() %>% 
  html_nodes(xpath = '//*[@id="tablepress-2894"]') %>% 
  html_table(header = TRUE, fill = TRUE) %>% 
  .[[1]]

nasdaq_semicon_df <- nasdaq_semicon_tickers %>% 
  janitor::clean_names() %>% 
  as_tibble() %>% 
  mutate(exchange = "NASDAQ")

semicon_df <- bind_rows(nyse_semicon_df, nasdaq_semicon_df) %>% 
  select(exchange, ticker, name)

semicon_df
```

## 회사정보 {#listed-semiconductor-company-info}

```{r}

```



